:spring_boot_version: 2.5.0
:spring-boot: https://github.com/spring-projects/spring-boot
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot

== Belfast Met / Version 1 Academy

=== Client Simulation

==== Problem Statement

"Customer problem: We need a system to allow the general public to pay fines who have not paid their TV licesnses."

What we want to see:

* User Persona and User Research
* Wireframes / POCs
* How you manage / track your work
* What is the MVP?
* What can you get delivered by the end of the week?
* Presentation

Hint:

GDS - https://www.gov.uk/service-manual/service-standard

==== Things to Consider

* Understand users and their needs
* Think about security and protect users's privacy
* Choose the right tools and technology, think about open standards, common components and patterns

=== Java 

We will use the Liberica JDK 11 Java Runtime, https://bell-sw.com/.


=== Visual Studio Code

We will use Visual Studio Code as our IDE, https://code.visualstudio.com/, when working with Java.

* Spring Boot Extension Pack
* Spring Boot Dashboard
* Spring Boot Tools

=== Spring 

We will use Spring as the rapid development framework to create a Web Application for our Client Simulation.

* Spring, https://spring.io/
* Thymeleaf, https://www.thymeleaf.org/documentation.html
* Bootstrap, https://getbootstrap.com/docs/5.1/getting-started/introduction/

Important folders in our Spring project.

* Java web application files, complete\src\main\java\com\example\springboot.
* Theymeleaf HTML template files, complete\src\main\resources\templates.

=== Microsoft Azure

We will deploy our web application to Microsoft Azure, https://portal.azure.com.

=== Project Management

We will use Trello for planning and task management, https://trello.com.

=== Base Repository
The original project was forked from, https://github.com/spring-guides/gs-spring-boot.